//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gift
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public string nguoi_nhan_ten { get; set; }
        public string nguoi_nhan_sdt { get; set; }
        public string nguoi_nhan_dia_chi { get; set; }
        public string loi_nhan { get; set; }
    
        public virtual order order { get; set; }
    }
}
