//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int id { get; set; }
        public Nullable<int> don_hang_id { get; set; }
        public Nullable<int> san_pham_id { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<decimal> don_gia { get; set; }
        public Nullable<decimal> giam_gia { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
