//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_payments
    {
        public int id { get; set; }
        public string ten_phuong_thuc { get; set; }
        public string mo_ta { get; set; }
        public string stk { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
