//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_details = new HashSet<order_details>();
            this.carts = new HashSet<cart>();
            this.suppliers = new HashSet<supplier>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public string mo_ta { get; set; }
        [Range(1, double.MaxValue, ErrorMessage = "Giá phải lớn hơn hoặc bằng 1")]
        public decimal gia { get; set; }
        public string hinh_anh { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng tồn kho không thể âm")]
        public Nullable<int> so_luong_ton_kho { get; set; }
        [DataType(DataType.Date)]
        [CustomDateValidation(ErrorMessage = "Ngày nhập không thể là ngày trong tương lai")]
        public Nullable<System.DateTime> ngay_nhap_kho { get; set; }
        public Nullable<int> loai_hoa_id { get; set; }
        public Nullable<int> dip_phu_hop_id { get; set; }
        public string kich_thuoc { get; set; }
        public string id_gg { get; set; }
        public string mau_sac { get; set; }
    
        public virtual flower_types flower_types { get; set; }
        public virtual occasion occasion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier> suppliers { get; set; }
    }

    public class CustomDateValidation : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if (value is DateTime date && date > DateTime.Now)
            {
                return new ValidationResult(ErrorMessage);
            }
            return ValidationResult.Success;
        }
    }
}
