//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public promotion()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public string mo_ta { get; set; }
        public Nullable<System.DateTime> ngay_bat_dau { get; set; }
        public Nullable<System.DateTime> ngay_ket_thuc { get; set; }
        public string code_promotions { get; set; }
        public string value_promotions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
