//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public int id { get; set; }
        public string ten { get; set; }
        public string dia_chi { get; set; }
        public string so_dien_thoai { get; set; }
        public string email { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<int> san_pham_id { get; set; }
    
        public virtual product product { get; set; }
    }
}
