//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Trường này bắt buộc")]
        public string ten { get; set; }
        public string dia_chi { get; set; }
        [Required(ErrorMessage ="Trường này bắt buộc")]
        public string so_dien_thoai { get; set; }
        [Required(ErrorMessage = "Trường này bắt buộc")]
        public string email { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string id_google { get; set; }
        public string id_facebook { get; set; }
        public string vai_tro { get; set; }
        [Required(ErrorMessage = "Trường này bắt buộc")]
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
